{% set name = "pyiron_ontology" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_ontology-{{ version }}.tar.gz
  sha256: c3525f1f8c0892a25afbf1e1b84988a0469a9765f3a2773c202162d308709ab5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer
    - toml
    - numpy
    - owlready2
    - pandas
    - pint
  run:
    - python >={{ python_min }},<3.13
    - numpy >=1.26.3,<1.27.0
    - owlready2 ==0.46
    - openjdk  # required by owlready2
    - pandas >=2.1.4,<2.3.0
    - pint ==0.23

test:
  imports:
    - pyiron_ontology
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_ontology
  summary: pyiron_ontology - module extension to pyiron.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    pyiron_ontology provides owlready2-based ontologies and tools to leverage them for pyiron projects.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - jan-janssen
    - pyiron-runner
    - liamhuber
