{% set name = "pyiron_ontology" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_ontology-{{ version }}.tar.gz
  sha256: 736767d079921474392750cc7278f4a62317c16d5059499212a91c9a6320518c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.26.3
    - owlready2 >=0.45
    - openjdk  # required by owlready2
    - pandas >=2.1.4
    - pint >=0.23

test:
  imports:
    - pyiron_ontology
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_ontology
  summary: pyiron_ontology - module extension to pyiron.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    pyiron_ontology provides owlready2-based ontologies and tools to leverage them for pyiron projects.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - jan-janssen
    - pyiron-runner
    - liamhuber
